#!/bin/sh
#
#    powernap wrapper for backgrounding the python daemon
#    Copyright (C) 2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="powernap"

# Default to background running, allow foreground override
FOREGROUND=0
for arg in $@; do
	case $arg in
		-f|--foreground)
			FOREGROUND=1
		;;
	esac
done

if [ "$FOREGROUND" = "1" ]; then
	# Run in foreground
	exec /usr/lib/$PKG/$PKG.py
else
	# Run in background
	# TODO: Setup some logging to /var/log/$PKG?
	exec /usr/lib/$PKG/$PKG.py >/dev/null &2>1 &
fi
