.TH powernap 1 "9 Jun 2009" powernap "powernap"
.SH NAME
powernap \- configurable daemon that will run at a specified INTERVAL_SECONDS, executing an ACTION when all of a list of MONITORED_PROCESSES are missing from the system process table for a contiguous ABSENT_SECONDS.

.SH DESCRIPTION
powernap will run ACTION when none of a set of MONITORED_PROCESSES have executed for some number of ABSENT_SECONDS.

The powernap daemon will check the process table using "ps -eo args" every INTERVAL_SECONDS.  Note that MONITORED_PROCESSES taking less than INTERVAL_SECONDS to execute may be overlooked by powernap.  Choose your INTERVAL_SECONDS value accordingly.  These parameters are configured in \fI/etc/powernap/config\fP.

Use "ps -eo args" for sample output and development your regular expressions.

It acts as a sort of "screensaver" for servers, watching the process table for activity rather than the keyboard or mouse.  For instance, PowerNap can automatically "pm-suspend" a system if no instance of "kvm" runs for some contiguous block of "300" seconds, checking the process table every "10" seconds.

.TP
\fIhttp://launchpad.net/powernap\fP
.PD

.SH FILES
\fI/etc/powernap/config\fP, \fI/var/run/powernap.pid\fP

.SH SEE ALSO
\fBpgrep\fP(1)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
