#!/bin/sh
#
#    turn_off_cpus: This script turns off all the CPU's available, except
#    for CPU 0.
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Andres Rodriguez <andreserl@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set_cpu_online() {
	for cpu in /sys/devices/system/cpu/cpu*/online; do
		[ -w "$cpu" ] || continue
		echo $1 > $cpu
	done
}

help() {
	echo "Turns off all the CPU's (cores) available but CPU0."
}

case $1 in
	true)
		# If machine is a Desktop, delay the disabling of the CPU's because
		# this apparently causes gnome-settings-daemon to crash, and the
                # appearance template  does not get applied properly.
		# If gnome-settings-daemon or gdm upstart job/init script exist,
                # assume there's a desktop environment and sleep 10.
		if [ -e /usr/bin/gnome-settings-daemon ] || \
                   [ -f /etc/init/gdm.conf ] || [ -f /etc/init.d/gdm ]; then
			sleep 10
		fi

		# Disable CPU
		set_cpu_online 0 ;;
	false)
		# Enable CPU
		set_cpu_online 1 ;;
	help)
		help;;
	*)
		exit $NA ;;
esac
