#!/bin/sh
#
#    poweraware_smp_sched: Power Aware SMP Scheduler. Power-saving for
#                          Multi-code, Multi-Thread process scheduler.
#                          May impact performance of some applications.
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Andres Rodriguez <andreserl@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

tune_core="/sys/devices/system/cpu/sched_mc_power_savings"
tune_thread="/sys/devices/system/cpu/sched_smt_power_savings"

poweraware_smp_scheduler() {
	if [ -w $tune_core ]; then
		echo $1 > $tune_core
	fi

	if [ -w $tune_thread ]; then
		echo $1 > $tune_thread
	fi
}

help() {
	echo "Power aware SMP scheduler. Saves power for multi-core and multi-thread process scheduler."
}

case $1 in
	true)
		poweraware_smp_scheduler 1 ;;
	false)
		poweraware_smp_scheduler 0 ;;
	help)
		help;;
	*)
		exit $NA ;;
esac
