#!/bin/sh
#
#    lowest_cpu_freq: This script lowers the frequency of the cpus by changing
#                     the scaling_governor from "ondemand" to "powersave"
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Andres Rodriguez <andreserl@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set_cpu_governor() {
	for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
		[ -w "$cpu" ] || continue
		echo $1 > $cpu
	done
}

help() {
	echo "Lowers the CPU frequency to the minimum possible by changing the scaling governor from ondemand to powersave"
}

case $1 in
	true)
		# Change governor to powersave
		set_cpu_governor powersave ;;
	false)
                # Change governor to ondemand
		set_cpu_governor ondemand ;;
	help) help;;
	*)
		exit $NA ;;
esac
